name: CI
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        eclipse:
          - 4.32    # 2024-06
          - 4.31    # 2024-03
          - '4.30'  # 2023-12
          - 4.29    # 2023-09
          - 4.28    # 2023-06
          - 4.27    # 2023-03
          - 4.26    # 2022-12
          - 4.25    # 2022-09
          - 4.24    # 2022-06
          - 4.23    # 2022-03
          - 4.22    # 2021-12
          - 4.21    # 2021-09
          - '4.20'  # 2021-06
          - 4.19    # 2021-03
          - 4.18    # 2020-12
          - 4.17    # 2020-09
          - 4.16    # 2020-06
          - 4.15    # 2020-03
          - 4.14    # 2019-12
          - 4.13    # 2019-09
          - 4.12    # 2019-06
          #- 4.11    # 2019-03 TODO PackageFragmentRootAnalyzerTest
          #- '4.10'  # 2018-12 TODO TypeTraverserTest
          - 4.9     # 2018-09
          - 4.8
          ## SEE branch `simrel_old`
          #- 4.7
          #- 4.6
          #- 4.5
          #- 4.4
          #- 4.3
          #- 3.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            export DISPLAY=:99.0
            Xvfb $DISPLAY &
          fi
          mvn -V -B -e verify -Pe${{ matrix.eclipse }} -Dtycho.executionEnvironment=JavaSE-17 -DskipUITests=false --no-transfer-progress
