name: CI
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        eclipse: [4.12, 4.13, 4.14, 4.15, 4.16, 4.17, 4.18, 4.19, '4.20', 4.21, 4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28, 4.29, '4.30']
        include:
          - eclipse: 4.12
            java: 11
          - eclipse: 4.13
            java: 11
          - eclipse: 4.14
            java: 11
          - eclipse: 4.15
            java: 11
          - eclipse: 4.16
            java: 11
          - eclipse: 4.17
            java: 11
          - eclipse: 4.18
            java: 11
          - eclipse: 4.19
            java: 11
          - eclipse: '4.20'
            java: 11
          - eclipse: 4.21
            java: 11
          - eclipse: 4.22
            java: 11
          - eclipse: 4.23
            java: 11
          - eclipse: 4.24
            java: 11
          # Java 17 since 4.25 (2022-09)
          - eclipse: 4.25
            java: 17
          - eclipse: 4.26
            java: 17
          - eclipse: 4.27
            java: 17
          - eclipse: 4.28
            java: 17
          - eclipse: 4.29
            java: 17
          - eclipse: '4.30'
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build
        shell: bash
        run: |
          mvn -V -B -e verify -Pe${{ matrix.eclipse }} -Dtarget-platform=eclemma-e${{ matrix.eclipse }} -Dtycho.executionEnvironment=JavaSE-${{ matrix.java }} -DskipUITests=false
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.os }} ${{ matrix.eclipse }}
          retention-days: 2
          path: |
            org.eclipse.eclemma.ui.test/target/work/data/.metadata/.log
            org.eclipse.eclemma.ui.test/target/screenshots
