name: CI
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - eclipse: 4.12
            java: 11
          - eclipse: 4.13
            java: 11
          - eclipse: 4.14
            java: 11
          - eclipse: 4.15
            java: 11
          - eclipse: 4.16
            java: 11
          - eclipse: 4.17
            java: 11
          - eclipse: 4.18
            java: 11
          - eclipse: 4.19
            java: 11
          - eclipse: '4.20'
            java: 11
          - eclipse: 4.21
            java: 11
          - eclipse: 4.22
            java: 11
          - eclipse: 4.23
            java: 11
          - eclipse: 4.24
            java: 11
          # Java 17 since 4.25 (2022-09)
          - eclipse: 4.25
            java: 17
          - eclipse: 4.26
            java: 17
          - eclipse: 4.27
            java: 17
          - eclipse: 4.28
            java: 17
          - eclipse: 4.29
            java: 17
          - eclipse: '4.30'
            java: 17
    runs-on: macos-latest
    #runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          #export DISPLAY=:99.0
          #Xvfb :99 &
          #sleep 5
          mvn -V -B -e verify -Pe${{ matrix.eclipse }} -Dtarget-platform=eclemma-e${{ matrix.eclipse }} -Dtycho.executionEnvironment=JavaSE-${{ matrix.java }} -DskipUITests=false
