name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: 11
      - name: Build
        shell: bash
        run: |
          mvn -V -B -e verify -Pe4.12 -Dtycho.executionEnvironment=JavaSE-11 -DskipUITests=false
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          retention-days: 2
          path: |
            org.eclipse.eclemma.ui.test/target/work/data/.metadata/.log
            org.eclipse.eclemma.ui.test/target/screenshots
