name: CI
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            export DISPLAY=:99.0
            Xvfb $DISPLAY &
          fi
          ./mvnw -V -B -e verify -Pe4.34 -Dtycho.executionEnvironment=JavaSE-21 -DskipUITests=false --no-transfer-progress
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          retention-days: 2
          path: |
            org.eclipse.eclemma.ui.test/target/work/data/.metadata/.log
            org.eclipse.eclemma.ui.test/target/screenshots
